define([
	'parentController',
	'headController', 
	'homePageController',
	'categoryController', 
	'payConfirmController', 
	'productPageController',
	'advertisementController',
	'recommendController',
	'footController',
	'finacialPageController',
    'bindingCardController',
	'orderCompleteController',
	'userCenterController',
	'withdrawController',
	'tradepwController',
	'aboutusController',
	], function(){
});